
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 01 16:14:45 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ClassSymbol {
  /* terminals */
  public static final int LANGAGESYMBOLES = 6;
  public static final int FONCTION = 4;
  public static final int PROCEDURE = 3;
  public static final int error = 1;
  public static final int STRING_LITERAL = 7;
  public static final int EOF = 0;
  public static final int OPERATORS = 5;
  public static final int TYPE = 2;
}

