
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 16 11:50:34 CET 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ClassSymbol {
  /* terminals */
  public static final int IDENTIFICATEUR = 10;
  public static final int POURCENT = 43;
  public static final int ETOILE = 41;
  public static final int STRING_LITERAL = 3;
  public static final int FUNCTION = 16;
  public static final int CARACTERE = 4;
  public static final int DEC_OP = 54;
  public static final int LISTOF = 11;
  public static final int PARENTHESE_OUVRANTE = 33;
  public static final int EGAL = 32;
  public static final int VIRGULE_FLOTTANTE = 6;
  public static final int POINT_VIRGULE = 27;
  public static final int DEUX_POINT = 31;
  public static final int REPEAT = 24;
  public static final int INC_OP = 53;
  public static final int VIRGULE = 30;
  public static final int TILDE = 38;
  public static final int GE_OP = 58;
  public static final int STATIC = 12;
  public static final int SUB_ASSIGN = 49;
  public static final int CROCHET_FERMANT = 36;
  public static final int TYPE = 14;
  public static final int NE_OP = 60;
  public static final int IN = 22;
  public static final int CADRATIN = 39;
  public static final int CLASS = 15;
  public static final int OR_OP = 56;
  public static final int PLUS = 40;
  public static final int ACCOLADE_FERMANTE = 29;
  public static final int EXCLAMATION = 37;
  public static final int IF = 25;
  public static final int TYPESIMPLE = 2;
  public static final int AND_OP = 55;
  public static final int ADD_ASSIGN = 48;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int TRUE = 7;
  public static final int CHEVRON_SUPERIEUR = 45;
  public static final int BARRE_OBLIQUE = 42;
  public static final int error = 1;
  public static final int CROCHET_OUVRANT = 35;
  public static final int NULL = 9;
  public static final int BREAK = 18;
  public static final int MOD_ASSIGN = 52;
  public static final int DIV_ASSIGN = 51;
  public static final int PARENTHESE_FERMANTE = 34;
  public static final int CIRCONFLEXE = 46;
  public static final int CHEVRON_INFERIEUR = 44;
  public static final int FOREACH = 21;
  public static final int ELSE = 26;
  public static final int STOP = 19;
  public static final int EQ_OP = 59;
  public static final int POINT = 47;
  public static final int WHILE = 23;
  public static final int STRUCTURE = 13;
  public static final int MUL_ASSIGN = 50;
  public static final int ACCOLADE_OUVRANTE = 28;
  public static final int ENTIER = 5;
  public static final int LE_OP = 57;
  public static final int FALSE = 8;
  public static final int PROCEDURE = 17;
}

